#
# Module manifest for module 'NamedPipe'
#
# Generated by: RayG
#
# Generated on: 07/07/2024
#

@{
	RootModule        = 'InitialiseModule.psm1'
	ModuleVersion     = '0.8'
	GUID              = 'b2a14d3e-8c7f-4e91-b035-7d2f9a1c4e56'
	Author            = 'RayG'
	CompanyName       = 'RayG'
	Copyright         = '(c) 2024-2026 RayG. All rights reserved.'
	Description       = 'Creates a named pipe server and client with chunked data transfer support for large objects.'
	PowerShellVersion = '5.0'
	RequiredModules   = @(
		@{
			ModuleName    = 'Microsoft.PowerShell.Security'
			ModuleVersion = '3.0.0.0'
		}
	)
	ModuleList        = @()
	FileList          = @()
	PrivateData       = @{
		ModuleName                 = 'NamedPipe'
		ModuleVars                 = @{
			''      = @{
				1 = 'DefineVariables.ps1'
			}
			Windows = @{
				1 = 'DefineVariablesCommon.ps1'
				2 = 'DefineVariablesPipe.ps1'
				3 = 'DefineVariablesSetWindow.ps1'
			}
			Linux   = @{}
			MacOS   = @{}
		}
		InitFunctions              = @{
			''      = @{}
			Windows = @{
				1 = @{
					Function = 'Set-Window'
					Params   = @{
						ProcessId  = 'pid'
						Characters = $true
					}
				}
			}
			Linux   = @{}
			MacOS   = @{}
		}
	}
}
